// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type FaceDetected struct {
	FaceDetected bool `json:"faceDetected"`
}

type Image struct {
	ID           int           `json:"id"`
	Filename     string        `json:"filename"`
	FaceDetected *FaceDetected `json:"faceDetected"`
}
