// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Detection struct {
	ID      int     `json:"id"`
	ImageID int     `json:"imageId"`
	Person  float64 `json:"person"`
	Image   *Image  `json:"image"`
}

type Image struct {
	ID        int        `json:"id"`
	Filename  string     `json:"filename"`
	Detection *Detection `json:"detection"`
}
