// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type Detection struct {
	Person float64 `json:"person"`
}

type Image struct {
	ID        int        `json:"id"`
	Filename  string     `json:"filename"`
	Detection *Detection `json:"Detection"`
}
