// Code generated by github.com/Khan/genqlient, DO NOT EDIT.

package qlient

import (
	"context"

	"github.com/Khan/genqlient/graphql"
)

// AddDetectionAddDetection includes the requested fields of the GraphQL type Detection.
type AddDetectionAddDetection struct {
	Person float64 `json:"person"`
}

// GetPerson returns AddDetectionAddDetection.Person, and is useful for accessing the field via an interface.
func (v *AddDetectionAddDetection) GetPerson() float64 { return v.Person }

// AddDetectionResponse is returned by AddDetection on success.
type AddDetectionResponse struct {
	AddDetection AddDetectionAddDetection `json:"addDetection"`
}

// GetAddDetection returns AddDetectionResponse.AddDetection, and is useful for accessing the field via an interface.
func (v *AddDetectionResponse) GetAddDetection() AddDetectionAddDetection { return v.AddDetection }

// AddImageAddImage includes the requested fields of the GraphQL type Image.
type AddImageAddImage struct {
	Id       int    `json:"id"`
	Filename string `json:"filename"`
}

// GetId returns AddImageAddImage.Id, and is useful for accessing the field via an interface.
func (v *AddImageAddImage) GetId() int { return v.Id }

// GetFilename returns AddImageAddImage.Filename, and is useful for accessing the field via an interface.
func (v *AddImageAddImage) GetFilename() string { return v.Filename }

// AddImageResponse is returned by AddImage on success.
type AddImageResponse struct {
	AddImage AddImageAddImage `json:"addImage"`
}

// GetAddImage returns AddImageResponse.AddImage, and is useful for accessing the field via an interface.
func (v *AddImageResponse) GetAddImage() AddImageAddImage { return v.AddImage }

// ImageFilenameImage includes the requested fields of the GraphQL type Image.
type ImageFilenameImage struct {
	Filename string `json:"filename"`
}

// GetFilename returns ImageFilenameImage.Filename, and is useful for accessing the field via an interface.
func (v *ImageFilenameImage) GetFilename() string { return v.Filename }

// ImageFilenameResponse is returned by ImageFilename on success.
type ImageFilenameResponse struct {
	Image ImageFilenameImage `json:"image"`
}

// GetImage returns ImageFilenameResponse.Image, and is useful for accessing the field via an interface.
func (v *ImageFilenameResponse) GetImage() ImageFilenameImage { return v.Image }

// ImageImage includes the requested fields of the GraphQL type Image.
type ImageImage struct {
	Id        int                 `json:"id"`
	Filename  string              `json:"filename"`
	Detection ImageImageDetection `json:"Detection"`
}

// GetId returns ImageImage.Id, and is useful for accessing the field via an interface.
func (v *ImageImage) GetId() int { return v.Id }

// GetFilename returns ImageImage.Filename, and is useful for accessing the field via an interface.
func (v *ImageImage) GetFilename() string { return v.Filename }

// GetDetection returns ImageImage.Detection, and is useful for accessing the field via an interface.
func (v *ImageImage) GetDetection() ImageImageDetection { return v.Detection }

// ImageImageDetection includes the requested fields of the GraphQL type Detection.
type ImageImageDetection struct {
	Person float64 `json:"person"`
}

// GetPerson returns ImageImageDetection.Person, and is useful for accessing the field via an interface.
func (v *ImageImageDetection) GetPerson() float64 { return v.Person }

// ImageResponse is returned by Image on success.
type ImageResponse struct {
	Image ImageImage `json:"image"`
}

// GetImage returns ImageResponse.Image, and is useful for accessing the field via an interface.
func (v *ImageResponse) GetImage() ImageImage { return v.Image }

// ImagesImagesImage includes the requested fields of the GraphQL type Image.
type ImagesImagesImage struct {
	Id        int                        `json:"id"`
	Filename  string                     `json:"filename"`
	Detection ImagesImagesImageDetection `json:"Detection"`
}

// GetId returns ImagesImagesImage.Id, and is useful for accessing the field via an interface.
func (v *ImagesImagesImage) GetId() int { return v.Id }

// GetFilename returns ImagesImagesImage.Filename, and is useful for accessing the field via an interface.
func (v *ImagesImagesImage) GetFilename() string { return v.Filename }

// GetDetection returns ImagesImagesImage.Detection, and is useful for accessing the field via an interface.
func (v *ImagesImagesImage) GetDetection() ImagesImagesImageDetection { return v.Detection }

// ImagesImagesImageDetection includes the requested fields of the GraphQL type Detection.
type ImagesImagesImageDetection struct {
	Person float64 `json:"person"`
}

// GetPerson returns ImagesImagesImageDetection.Person, and is useful for accessing the field via an interface.
func (v *ImagesImagesImageDetection) GetPerson() float64 { return v.Person }

// ImagesResponse is returned by Images on success.
type ImagesResponse struct {
	Images []ImagesImagesImage `json:"images"`
}

// GetImages returns ImagesResponse.Images, and is useful for accessing the field via an interface.
func (v *ImagesResponse) GetImages() []ImagesImagesImage { return v.Images }

// __AddDetectionInput is used internally by genqlient
type __AddDetectionInput struct {
	ImageId int     `json:"imageId"`
	Person  float64 `json:"person"`
}

// GetImageId returns __AddDetectionInput.ImageId, and is useful for accessing the field via an interface.
func (v *__AddDetectionInput) GetImageId() int { return v.ImageId }

// GetPerson returns __AddDetectionInput.Person, and is useful for accessing the field via an interface.
func (v *__AddDetectionInput) GetPerson() float64 { return v.Person }

// __AddImageInput is used internally by genqlient
type __AddImageInput struct {
	Filename string `json:"filename"`
}

// GetFilename returns __AddImageInput.Filename, and is useful for accessing the field via an interface.
func (v *__AddImageInput) GetFilename() string { return v.Filename }

// __ImageFilenameInput is used internally by genqlient
type __ImageFilenameInput struct {
	ImageId int `json:"imageId"`
}

// GetImageId returns __ImageFilenameInput.ImageId, and is useful for accessing the field via an interface.
func (v *__ImageFilenameInput) GetImageId() int { return v.ImageId }

// __ImageInput is used internally by genqlient
type __ImageInput struct {
	ImageId int `json:"imageId"`
}

// GetImageId returns __ImageInput.ImageId, and is useful for accessing the field via an interface.
func (v *__ImageInput) GetImageId() int { return v.ImageId }

func AddDetection(
	ctx context.Context,
	client graphql.Client,
	imageId int,
	person float64,
) (*AddDetectionResponse, error) {
	req := &graphql.Request{
		OpName: "AddDetection",
		Query: `
mutation AddDetection ($imageId: Int!, $person: Float!) {
	addDetection(imageId: $imageId, person: $person) {
		person
	}
}
`,
		Variables: &__AddDetectionInput{
			ImageId: imageId,
			Person:  person,
		},
	}
	var err error

	var data AddDetectionResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

func AddImage(
	ctx context.Context,
	client graphql.Client,
	filename string,
) (*AddImageResponse, error) {
	req := &graphql.Request{
		OpName: "AddImage",
		Query: `
mutation AddImage ($filename: String!) {
	addImage(filename: $filename) {
		id
		filename
	}
}
`,
		Variables: &__AddImageInput{
			Filename: filename,
		},
	}
	var err error

	var data AddImageResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

func Image(
	ctx context.Context,
	client graphql.Client,
	imageId int,
) (*ImageResponse, error) {
	req := &graphql.Request{
		OpName: "Image",
		Query: `
query Image ($imageId: Int!) {
	image(imageId: $imageId) {
		id
		filename
		Detection {
			person
		}
	}
}
`,
		Variables: &__ImageInput{
			ImageId: imageId,
		},
	}
	var err error

	var data ImageResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

func ImageFilename(
	ctx context.Context,
	client graphql.Client,
	imageId int,
) (*ImageFilenameResponse, error) {
	req := &graphql.Request{
		OpName: "ImageFilename",
		Query: `
query ImageFilename ($imageId: Int!) {
	image(imageId: $imageId) {
		filename
	}
}
`,
		Variables: &__ImageFilenameInput{
			ImageId: imageId,
		},
	}
	var err error

	var data ImageFilenameResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}

func Images(
	ctx context.Context,
	client graphql.Client,
) (*ImagesResponse, error) {
	req := &graphql.Request{
		OpName: "Images",
		Query: `
query Images {
	images {
		id
		filename
		Detection {
			person
		}
	}
}
`,
	}
	var err error

	var data ImagesResponse
	resp := &graphql.Response{Data: &data}

	err = client.MakeRequest(
		ctx,
		req,
		resp,
	)

	return &data, err
}
